create table USER
(
	ID BIGINT auto_increment primary key not null,
	ACCOUNT_ID VARCHAR(100),
	NAME VARCHAR(50),
	TOKEN CHAR(36),
	GMT_CREATE BIGINT,
	GMT_MODIFY BIGINT,
	THIRDPARTY VARCHAR(50),
	BIO VARCHAR(256)
);

